benchmarks:
# - benchmark_name: ppermute
#   benchmark_sweep_params:
#   - {matrix_dim_range: {start: 1024, end: 29696, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 128}
#   xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 128, end: 32768, multiplier: 2}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 128, num_runs: 100}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
- benchmark_name: psum
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 29696, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 128, num_runs: 100}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
- benchmark_name: psum_scatter
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 29696, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 128, num_runs: 100}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 29696, increase_by: 1024}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 128, num_runs: 100}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
